server.port : 5000

spring:
  config:
    import:
      - application-db.yml
      - application-security.yml
  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false
